package dice.game;

public interface Player {
    /**
     * Method to get total game won of each Player
     * @return number of won games
     */
    int getGamesWon();

    /**
     * Method to get score on current throw.
     * @return score on current throw
     */
    int getCurrentThrow();

    /** Method incrementing a <b>gamesWon</b> - called in case of winning a throw */
    void winThrow();

    /**
     * Sets scored points in a current Throw
     * @param currentThrow sum of points in a currentThrow, generated by class <b>Dice</b>
     * @see Dice
     */
    void setCurrentThrow(int currentThrow);

    /**
     * Method to get Player's name
     * @return Player's name
     */
    String getName();
}

